# Generated by Django 3.1.2 on 2020-11-21 02:54

from django.db import migrations, models

import dynamic_storages.fields.encrypted_json


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestEncryptedJSONField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", dynamic_storages.fields.encrypted_json.EncryptedJSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
