# Generated by Django 3.1.2 on 2020-11-21 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_testencryptedjsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testencryptedfilefieldmodel",
            name="storage_target",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tests.teststoragetarget"),
        ),
        migrations.AlterField(
            model_name="testencryptedimagefieldmodel",
            name="storage_target",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tests.teststoragetarget"),
        ),
        migrations.AlterField(
            model_name="testfilestoragemodel",
            name="storage_target",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tests.teststoragetarget"),
        ),
        migrations.AlterField(
            model_name="testimagestoragemodel",
            name="storage_target",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tests.teststoragetarget"),
        ),
    ]
